### ISSUE TITLE
Mettre à jour le README

### ISSUE THREAD

**Issue by bzg** [etalab/entraide.etalab.studio#1]
- Faire un `README` en français
- Expliquer que ce dépôt s'appuie sur `question2answer`
- Et qu'il propose un nouveau thème accessible et reprenant le design système de l'Etat
- Ajouter une section "Licence et contribution" précisant la licence et que les contributions sont bienvenues

**Comment by Balaiseee** [comment]
> * Faire un `README` en français
> 
> * Expliquer que ce dépôt s'appuie sur `question2answer`
> 
> * Et qu'il propose un nouveau thème accessible et reprenant le design système de l'Etat
> 
> * Ajouter une section "Licence et contribution" précisant la licence et que les contributions sont bienvenues

C'est bon ! :)
